// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: pb/admin.proto

package geocube

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//*
// Request to remove from the database all the pending entities (entities that are not linked to any dataset)
type TidyDBRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Simulate          bool `protobuf:"varint,1,opt,name=Simulate,proto3" json:"Simulate,omitempty"`                   // If true, a simulation is done, nothing is actually deleted
	PendingAOIs       bool `protobuf:"varint,2,opt,name=PendingAOIs,proto3" json:"PendingAOIs,omitempty"`             // Remove AOIs that are not linked to any Records
	PendingRecords    bool `protobuf:"varint,3,opt,name=PendingRecords,proto3" json:"PendingRecords,omitempty"`       // Remove Records that do not reference any Datasets
	PendingVariables  bool `protobuf:"varint,4,opt,name=PendingVariables,proto3" json:"PendingVariables,omitempty"`   // Remove Variables that have not any instances
	PendingInstances  bool `protobuf:"varint,5,opt,name=PendingInstances,proto3" json:"PendingInstances,omitempty"`   // Remove Instances that do not reference any Datasets
	PendingContainers bool `protobuf:"varint,6,opt,name=PendingContainers,proto3" json:"PendingContainers,omitempty"` // Remove Containers that do not contain any Datasets
	PendingParams     bool `protobuf:"varint,7,opt,name=PendingParams,proto3" json:"PendingParams,omitempty"`         // Remove ConsolidationParams that are not linked to any Variable or Job
}

func (x *TidyDBRequest) Reset() {
	*x = TidyDBRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_admin_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TidyDBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TidyDBRequest) ProtoMessage() {}

func (x *TidyDBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_admin_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TidyDBRequest.ProtoReflect.Descriptor instead.
func (*TidyDBRequest) Descriptor() ([]byte, []int) {
	return file_pb_admin_proto_rawDescGZIP(), []int{0}
}

func (x *TidyDBRequest) GetSimulate() bool {
	if x != nil {
		return x.Simulate
	}
	return false
}

func (x *TidyDBRequest) GetPendingAOIs() bool {
	if x != nil {
		return x.PendingAOIs
	}
	return false
}

func (x *TidyDBRequest) GetPendingRecords() bool {
	if x != nil {
		return x.PendingRecords
	}
	return false
}

func (x *TidyDBRequest) GetPendingVariables() bool {
	if x != nil {
		return x.PendingVariables
	}
	return false
}

func (x *TidyDBRequest) GetPendingInstances() bool {
	if x != nil {
		return x.PendingInstances
	}
	return false
}

func (x *TidyDBRequest) GetPendingContainers() bool {
	if x != nil {
		return x.PendingContainers
	}
	return false
}

func (x *TidyDBRequest) GetPendingParams() bool {
	if x != nil {
		return x.PendingParams
	}
	return false
}

//*
// Return the number of entities that were deleted (or should have been deleted if Simulate=True)
type TidyDBResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NbAOIs       int64 `protobuf:"varint,1,opt,name=NbAOIs,proto3" json:"NbAOIs,omitempty"`
	NbRecords    int64 `protobuf:"varint,2,opt,name=NbRecords,proto3" json:"NbRecords,omitempty"`
	NbVariables  int64 `protobuf:"varint,3,opt,name=NbVariables,proto3" json:"NbVariables,omitempty"`
	NbInstances  int64 `protobuf:"varint,4,opt,name=NbInstances,proto3" json:"NbInstances,omitempty"`
	NbContainers int64 `protobuf:"varint,5,opt,name=NbContainers,proto3" json:"NbContainers,omitempty"`
	NbParams     int64 `protobuf:"varint,6,opt,name=NbParams,proto3" json:"NbParams,omitempty"`
}

func (x *TidyDBResponse) Reset() {
	*x = TidyDBResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_admin_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TidyDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TidyDBResponse) ProtoMessage() {}

func (x *TidyDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_admin_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TidyDBResponse.ProtoReflect.Descriptor instead.
func (*TidyDBResponse) Descriptor() ([]byte, []int) {
	return file_pb_admin_proto_rawDescGZIP(), []int{1}
}

func (x *TidyDBResponse) GetNbAOIs() int64 {
	if x != nil {
		return x.NbAOIs
	}
	return 0
}

func (x *TidyDBResponse) GetNbRecords() int64 {
	if x != nil {
		return x.NbRecords
	}
	return 0
}

func (x *TidyDBResponse) GetNbVariables() int64 {
	if x != nil {
		return x.NbVariables
	}
	return 0
}

func (x *TidyDBResponse) GetNbInstances() int64 {
	if x != nil {
		return x.NbInstances
	}
	return 0
}

func (x *TidyDBResponse) GetNbContainers() int64 {
	if x != nil {
		return x.NbContainers
	}
	return 0
}

func (x *TidyDBResponse) GetNbParams() int64 {
	if x != nil {
		return x.NbParams
	}
	return 0
}

//*
// Update fields of datasets that can be tricky
type UpdateDatasetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Simulate     bool        `protobuf:"varint,1,opt,name=simulate,proto3" json:"simulate,omitempty"`                                 // If true, a simulation is done, nothing is actually updated
	InstanceId   string      `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`            // Instance id that references the datasets to be updated
	RecordIds    []string    `protobuf:"bytes,3,rep,name=record_ids,json=recordIds,proto3" json:"record_ids,omitempty"`               // Record ids that reference the datasets to be updated
	Dformat      *DataFormat `protobuf:"bytes,8,opt,name=dformat,proto3" json:"dformat,omitempty"`                                    // Internal data format (DType can be Undefined)
	RealMinValue float64     `protobuf:"fixed64,9,opt,name=real_min_value,json=realMinValue,proto3" json:"real_min_value,omitempty"`  // Real min value (dformat.min_value maps to real_min_value)
	RealMaxValue float64     `protobuf:"fixed64,10,opt,name=real_max_value,json=realMaxValue,proto3" json:"real_max_value,omitempty"` // Real max value (dformat.max_value maps to real_max_value)
	Exponent     float64     `protobuf:"fixed64,11,opt,name=exponent,proto3" json:"exponent,omitempty"`                               // 1: linear scaling (RealMax - RealMin) * pow( (Value - Min) / (Max - Min), Exponent) + RealMin
}

func (x *UpdateDatasetsRequest) Reset() {
	*x = UpdateDatasetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_admin_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatasetsRequest) ProtoMessage() {}

func (x *UpdateDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_admin_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatasetsRequest.ProtoReflect.Descriptor instead.
func (*UpdateDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_pb_admin_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateDatasetsRequest) GetSimulate() bool {
	if x != nil {
		return x.Simulate
	}
	return false
}

func (x *UpdateDatasetsRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *UpdateDatasetsRequest) GetRecordIds() []string {
	if x != nil {
		return x.RecordIds
	}
	return nil
}

func (x *UpdateDatasetsRequest) GetDformat() *DataFormat {
	if x != nil {
		return x.Dformat
	}
	return nil
}

func (x *UpdateDatasetsRequest) GetRealMinValue() float64 {
	if x != nil {
		return x.RealMinValue
	}
	return 0
}

func (x *UpdateDatasetsRequest) GetRealMaxValue() float64 {
	if x != nil {
		return x.RealMaxValue
	}
	return 0
}

func (x *UpdateDatasetsRequest) GetExponent() float64 {
	if x != nil {
		return x.Exponent
	}
	return 0
}

//*
// Return the number of modifications per kind of modification
type UpdateDatasetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results map[string]int64 `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *UpdateDatasetsResponse) Reset() {
	*x = UpdateDatasetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_admin_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDatasetsResponse) ProtoMessage() {}

func (x *UpdateDatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_admin_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDatasetsResponse.ProtoReflect.Descriptor instead.
func (*UpdateDatasetsResponse) Descriptor() ([]byte, []int) {
	return file_pb_admin_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateDatasetsResponse) GetResults() map[string]int64 {
	if x != nil {
		return x.Results
	}
	return nil
}

//*
// Remove the datasets referenced by instances and records without any control
// The containers (if empty) are not deleted
type DeleteDatasetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//bool            simulate     = 1; // DEPRECATED If true, a simulation is done, nothing is actually deleted. Use StepByStep=2 instead
	RecordIds   []string `protobuf:"bytes,2,rep,name=record_ids,json=recordIds,proto3" json:"record_ids,omitempty"`       // Instance id that references the datasets to be deleted
	InstanceIds []string `protobuf:"bytes,3,rep,name=instance_ids,json=instanceIds,proto3" json:"instance_ids,omitempty"` // Record ids that reference the datasets to be deleted
	StepByStep  int32    `protobuf:"varint,4,opt,name=step_by_step,json=stepByStep,proto3" json:"step_by_step,omitempty"` // by default 0, 1: critical steps, 2: major steps, 3: all steps
	JobName     string   `protobuf:"bytes,5,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`             // Name of the job (if empty, a name will be generated)
}

func (x *DeleteDatasetsRequest) Reset() {
	*x = DeleteDatasetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_admin_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDatasetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatasetsRequest) ProtoMessage() {}

func (x *DeleteDatasetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_admin_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatasetsRequest.ProtoReflect.Descriptor instead.
func (*DeleteDatasetsRequest) Descriptor() ([]byte, []int) {
	return file_pb_admin_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDatasetsRequest) GetRecordIds() []string {
	if x != nil {
		return x.RecordIds
	}
	return nil
}

func (x *DeleteDatasetsRequest) GetInstanceIds() []string {
	if x != nil {
		return x.InstanceIds
	}
	return nil
}

func (x *DeleteDatasetsRequest) GetStepByStep() int32 {
	if x != nil {
		return x.StepByStep
	}
	return 0
}

func (x *DeleteDatasetsRequest) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

//*
// Return the number of deleted datasets
type DeleteDatasetsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//repeated string results = 1; // DEPRECATED: use the log of the job
	Job *Job `protobuf:"bytes,2,opt,name=job,proto3" json:"job,omitempty"`
}

func (x *DeleteDatasetsResponse) Reset() {
	*x = DeleteDatasetsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_admin_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDatasetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDatasetsResponse) ProtoMessage() {}

func (x *DeleteDatasetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_admin_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDatasetsResponse.ProtoReflect.Descriptor instead.
func (*DeleteDatasetsResponse) Descriptor() ([]byte, []int) {
	return file_pb_admin_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteDatasetsResponse) GetJob() *Job {
	if x != nil {
		return x.Job
	}
	return nil
}

var File_pb_admin_proto protoreflect.FileDescriptor

var file_pb_admin_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x62, 0x2f, 0x61, 0x64, 0x6d, 0x69, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x07, 0x67, 0x65, 0x6f, 0x63, 0x75, 0x62, 0x65, 0x1a, 0x13, 0x70, 0x62, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13,
	0x70, 0x62, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x02, 0x0a, 0x0d, 0x54, 0x69, 0x64, 0x79, 0x44, 0x42, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74,
	0x65, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x4f, 0x49, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x41,
	0x4f, 0x49, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x50, 0x65, 0x6e,
	0x64, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x50,
	0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x50, 0x65, 0x6e, 0x64, 0x69,
	0x6e, 0x67, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x10, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x73, 0x12, 0x2c, 0x0a, 0x11, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x11,
	0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72,
	0x73, 0x12, 0x24, 0x0a, 0x0d, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x50, 0x65, 0x6e, 0x64, 0x69, 0x6e,
	0x67, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0xca, 0x01, 0x0a, 0x0e, 0x54, 0x69, 0x64, 0x79,
	0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x62,
	0x41, 0x4f, 0x49, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x4e, 0x62, 0x41, 0x4f,
	0x49, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x4e, 0x62, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x4e, 0x62, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x73,
	0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x62, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x4e, 0x62, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x62, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x4e, 0x62, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x4e, 0x62, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69,
	0x6e, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x4e, 0x62, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x62, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x4e, 0x62, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x22, 0x8a, 0x02, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x69, 0x6e,
	0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x73, 0x12, 0x2d, 0x0a, 0x07, 0x64, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x65,
	0x6f, 0x63, 0x75, 0x62, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x52, 0x07, 0x64, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x72, 0x65, 0x61,
	0x6c, 0x5f, 0x6d, 0x69, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x0c, 0x72, 0x65, 0x61, 0x6c, 0x4d, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x24, 0x0a, 0x0e, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x6d, 0x61, 0x78, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x01, 0x52, 0x0c, 0x72, 0x65, 0x61, 0x6c, 0x4d, 0x61, 0x78,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x65, 0x78, 0x70, 0x6f, 0x6e, 0x65, 0x6e,
	0x74, 0x22, 0x9c, 0x01, 0x0a, 0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e,
	0x67, 0x65, 0x6f, 0x63, 0x75, 0x62, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61,
	0x74, 0x61, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x96, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x73,
	0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x69, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0b, 0x69, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x73, 0x12, 0x20, 0x0a, 0x0c,
	0x73, 0x74, 0x65, 0x70, 0x5f, 0x62, 0x79, 0x5f, 0x73, 0x74, 0x65, 0x70, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x73, 0x74, 0x65, 0x70, 0x42, 0x79, 0x53, 0x74, 0x65, 0x70, 0x12, 0x19,
	0x0a, 0x08, 0x6a, 0x6f, 0x62, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6a, 0x6f, 0x62, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x16, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x67, 0x65, 0x6f, 0x63, 0x75, 0x62, 0x65, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x03,
	0x6a, 0x6f, 0x62, 0x32, 0xee, 0x01, 0x0a, 0x05, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x12, 0x3b, 0x0a,
	0x06, 0x54, 0x69, 0x64, 0x79, 0x44, 0x42, 0x12, 0x16, 0x2e, 0x67, 0x65, 0x6f, 0x63, 0x75, 0x62,
	0x65, 0x2e, 0x54, 0x69, 0x64, 0x79, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x67, 0x65, 0x6f, 0x63, 0x75, 0x62, 0x65, 0x2e, 0x54, 0x69, 0x64, 0x79, 0x44, 0x42,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x0e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x73, 0x12, 0x1e, 0x2e, 0x67,
	0x65, 0x6f, 0x63, 0x75, 0x62, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x67,
	0x65, 0x6f, 0x63, 0x75, 0x62, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x53, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74,
	0x73, 0x12, 0x1e, 0x2e, 0x67, 0x65, 0x6f, 0x63, 0x75, 0x62, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x67, 0x65, 0x6f, 0x63, 0x75, 0x62, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x73, 0x65, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x70, 0x62, 0x3b, 0x67, 0x65, 0x6f,
	0x63, 0x75, 0x62, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_admin_proto_rawDescOnce sync.Once
	file_pb_admin_proto_rawDescData = file_pb_admin_proto_rawDesc
)

func file_pb_admin_proto_rawDescGZIP() []byte {
	file_pb_admin_proto_rawDescOnce.Do(func() {
		file_pb_admin_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_admin_proto_rawDescData)
	})
	return file_pb_admin_proto_rawDescData
}

var file_pb_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pb_admin_proto_goTypes = []interface{}{
	(*TidyDBRequest)(nil),          // 0: geocube.TidyDBRequest
	(*TidyDBResponse)(nil),         // 1: geocube.TidyDBResponse
	(*UpdateDatasetsRequest)(nil),  // 2: geocube.UpdateDatasetsRequest
	(*UpdateDatasetsResponse)(nil), // 3: geocube.UpdateDatasetsResponse
	(*DeleteDatasetsRequest)(nil),  // 4: geocube.DeleteDatasetsRequest
	(*DeleteDatasetsResponse)(nil), // 5: geocube.DeleteDatasetsResponse
	nil,                            // 6: geocube.UpdateDatasetsResponse.ResultsEntry
	(*DataFormat)(nil),             // 7: geocube.DataFormat
	(*Job)(nil),                    // 8: geocube.Job
}
var file_pb_admin_proto_depIdxs = []int32{
	7, // 0: geocube.UpdateDatasetsRequest.dformat:type_name -> geocube.DataFormat
	6, // 1: geocube.UpdateDatasetsResponse.results:type_name -> geocube.UpdateDatasetsResponse.ResultsEntry
	8, // 2: geocube.DeleteDatasetsResponse.job:type_name -> geocube.Job
	0, // 3: geocube.Admin.TidyDB:input_type -> geocube.TidyDBRequest
	2, // 4: geocube.Admin.UpdateDatasets:input_type -> geocube.UpdateDatasetsRequest
	4, // 5: geocube.Admin.DeleteDatasets:input_type -> geocube.DeleteDatasetsRequest
	1, // 6: geocube.Admin.TidyDB:output_type -> geocube.TidyDBResponse
	3, // 7: geocube.Admin.UpdateDatasets:output_type -> geocube.UpdateDatasetsResponse
	5, // 8: geocube.Admin.DeleteDatasets:output_type -> geocube.DeleteDatasetsResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pb_admin_proto_init() }
func file_pb_admin_proto_init() {
	if File_pb_admin_proto != nil {
		return
	}
	file_pb_dataformat_proto_init()
	file_pb_operations_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pb_admin_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TidyDBRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_admin_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TidyDBResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_admin_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDatasetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_admin_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDatasetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_admin_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDatasetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_admin_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDatasetsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_admin_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_admin_proto_goTypes,
		DependencyIndexes: file_pb_admin_proto_depIdxs,
		MessageInfos:      file_pb_admin_proto_msgTypes,
	}.Build()
	File_pb_admin_proto = out.File
	file_pb_admin_proto_rawDesc = nil
	file_pb_admin_proto_goTypes = nil
	file_pb_admin_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminClient interface {
	TidyDB(ctx context.Context, in *TidyDBRequest, opts ...grpc.CallOption) (*TidyDBResponse, error)
	UpdateDatasets(ctx context.Context, in *UpdateDatasetsRequest, opts ...grpc.CallOption) (*UpdateDatasetsResponse, error)
	DeleteDatasets(ctx context.Context, in *DeleteDatasetsRequest, opts ...grpc.CallOption) (*DeleteDatasetsResponse, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) TidyDB(ctx context.Context, in *TidyDBRequest, opts ...grpc.CallOption) (*TidyDBResponse, error) {
	out := new(TidyDBResponse)
	err := c.cc.Invoke(ctx, "/geocube.Admin/TidyDB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateDatasets(ctx context.Context, in *UpdateDatasetsRequest, opts ...grpc.CallOption) (*UpdateDatasetsResponse, error) {
	out := new(UpdateDatasetsResponse)
	err := c.cc.Invoke(ctx, "/geocube.Admin/UpdateDatasets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteDatasets(ctx context.Context, in *DeleteDatasetsRequest, opts ...grpc.CallOption) (*DeleteDatasetsResponse, error) {
	out := new(DeleteDatasetsResponse)
	err := c.cc.Invoke(ctx, "/geocube.Admin/DeleteDatasets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
type AdminServer interface {
	TidyDB(context.Context, *TidyDBRequest) (*TidyDBResponse, error)
	UpdateDatasets(context.Context, *UpdateDatasetsRequest) (*UpdateDatasetsResponse, error)
	DeleteDatasets(context.Context, *DeleteDatasetsRequest) (*DeleteDatasetsResponse, error)
}

// UnimplementedAdminServer can be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (*UnimplementedAdminServer) TidyDB(context.Context, *TidyDBRequest) (*TidyDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TidyDB not implemented")
}
func (*UnimplementedAdminServer) UpdateDatasets(context.Context, *UpdateDatasetsRequest) (*UpdateDatasetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDatasets not implemented")
}
func (*UnimplementedAdminServer) DeleteDatasets(context.Context, *DeleteDatasetsRequest) (*DeleteDatasetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDatasets not implemented")
}

func RegisterAdminServer(s *grpc.Server, srv AdminServer) {
	s.RegisterService(&_Admin_serviceDesc, srv)
}

func _Admin_TidyDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TidyDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).TidyDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geocube.Admin/TidyDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).TidyDB(ctx, req.(*TidyDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geocube.Admin/UpdateDatasets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateDatasets(ctx, req.(*UpdateDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geocube.Admin/DeleteDatasets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteDatasets(ctx, req.(*DeleteDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Admin_serviceDesc = grpc.ServiceDesc{
	ServiceName: "geocube.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TidyDB",
			Handler:    _Admin_TidyDB_Handler,
		},
		{
			MethodName: "UpdateDatasets",
			Handler:    _Admin_UpdateDatasets_Handler,
		},
		{
			MethodName: "DeleteDatasets",
			Handler:    _Admin_DeleteDatasets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/admin.proto",
}
