// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package geocube

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AdminClient is the client API for Admin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminClient interface {
	TidyDB(ctx context.Context, in *TidyDBRequest, opts ...grpc.CallOption) (*TidyDBResponse, error)
	UpdateDatasets(ctx context.Context, in *UpdateDatasetsRequest, opts ...grpc.CallOption) (*UpdateDatasetsResponse, error)
	DeleteDatasets(ctx context.Context, in *DeleteDatasetsRequest, opts ...grpc.CallOption) (*DeleteDatasetsResponse, error)
}

type adminClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminClient(cc grpc.ClientConnInterface) AdminClient {
	return &adminClient{cc}
}

func (c *adminClient) TidyDB(ctx context.Context, in *TidyDBRequest, opts ...grpc.CallOption) (*TidyDBResponse, error) {
	out := new(TidyDBResponse)
	err := c.cc.Invoke(ctx, "/geocube.Admin/TidyDB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) UpdateDatasets(ctx context.Context, in *UpdateDatasetsRequest, opts ...grpc.CallOption) (*UpdateDatasetsResponse, error) {
	out := new(UpdateDatasetsResponse)
	err := c.cc.Invoke(ctx, "/geocube.Admin/UpdateDatasets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminClient) DeleteDatasets(ctx context.Context, in *DeleteDatasetsRequest, opts ...grpc.CallOption) (*DeleteDatasetsResponse, error) {
	out := new(DeleteDatasetsResponse)
	err := c.cc.Invoke(ctx, "/geocube.Admin/DeleteDatasets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServer is the server API for Admin service.
// All implementations must embed UnimplementedAdminServer
// for forward compatibility
type AdminServer interface {
	TidyDB(context.Context, *TidyDBRequest) (*TidyDBResponse, error)
	UpdateDatasets(context.Context, *UpdateDatasetsRequest) (*UpdateDatasetsResponse, error)
	DeleteDatasets(context.Context, *DeleteDatasetsRequest) (*DeleteDatasetsResponse, error)
	mustEmbedUnimplementedAdminServer()
}

// UnimplementedAdminServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServer struct {
}

func (UnimplementedAdminServer) TidyDB(context.Context, *TidyDBRequest) (*TidyDBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TidyDB not implemented")
}
func (UnimplementedAdminServer) UpdateDatasets(context.Context, *UpdateDatasetsRequest) (*UpdateDatasetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDatasets not implemented")
}
func (UnimplementedAdminServer) DeleteDatasets(context.Context, *DeleteDatasetsRequest) (*DeleteDatasetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDatasets not implemented")
}
func (UnimplementedAdminServer) mustEmbedUnimplementedAdminServer() {}

// UnsafeAdminServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServer will
// result in compilation errors.
type UnsafeAdminServer interface {
	mustEmbedUnimplementedAdminServer()
}

func RegisterAdminServer(s grpc.ServiceRegistrar, srv AdminServer) {
	s.RegisterService(&Admin_ServiceDesc, srv)
}

func _Admin_TidyDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TidyDBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).TidyDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geocube.Admin/TidyDB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).TidyDB(ctx, req.(*TidyDBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_UpdateDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).UpdateDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geocube.Admin/UpdateDatasets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).UpdateDatasets(ctx, req.(*UpdateDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Admin_DeleteDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServer).DeleteDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/geocube.Admin/DeleteDatasets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServer).DeleteDatasets(ctx, req.(*DeleteDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Admin_ServiceDesc is the grpc.ServiceDesc for Admin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Admin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geocube.Admin",
	HandlerType: (*AdminServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TidyDB",
			Handler:    _Admin_TidyDB_Handler,
		},
		{
			MethodName: "UpdateDatasets",
			Handler:    _Admin_UpdateDatasets_Handler,
		},
		{
			MethodName: "DeleteDatasets",
			Handler:    _Admin_DeleteDatasets_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/admin.proto",
}
