// Code generated by "enumer -json -sql -type Compression -trimprefix Compression"; DO NOT EDIT.

package geocube

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"strings"
)

const _CompressionName = "NOLOSSLESSLOSSYCUSTOM"

var _CompressionIndex = [...]uint8{0, 2, 10, 15, 21}

const _CompressionLowerName = "nolosslesslossycustom"

func (i Compression) String() string {
	if i < 0 || i >= Compression(len(_CompressionIndex)-1) {
		return fmt.Sprintf("Compression(%d)", i)
	}
	return _CompressionName[_CompressionIndex[i]:_CompressionIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _CompressionNoOp() {
	var x [1]struct{}
	_ = x[CompressionNO-(0)]
	_ = x[CompressionLOSSLESS-(1)]
	_ = x[CompressionLOSSY-(2)]
	_ = x[CompressionCUSTOM-(3)]
}

var _CompressionValues = []Compression{CompressionNO, CompressionLOSSLESS, CompressionLOSSY, CompressionCUSTOM}

var _CompressionNameToValueMap = map[string]Compression{
	_CompressionName[0:2]:        CompressionNO,
	_CompressionLowerName[0:2]:   CompressionNO,
	_CompressionName[2:10]:       CompressionLOSSLESS,
	_CompressionLowerName[2:10]:  CompressionLOSSLESS,
	_CompressionName[10:15]:      CompressionLOSSY,
	_CompressionLowerName[10:15]: CompressionLOSSY,
	_CompressionName[15:21]:      CompressionCUSTOM,
	_CompressionLowerName[15:21]: CompressionCUSTOM,
}

var _CompressionNames = []string{
	_CompressionName[0:2],
	_CompressionName[2:10],
	_CompressionName[10:15],
	_CompressionName[15:21],
}

// CompressionString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func CompressionString(s string) (Compression, error) {
	if val, ok := _CompressionNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _CompressionNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Compression values", s)
}

// CompressionValues returns all values of the enum
func CompressionValues() []Compression {
	return _CompressionValues
}

// CompressionStrings returns a slice of all String values of the enum
func CompressionStrings() []string {
	strs := make([]string, len(_CompressionNames))
	copy(strs, _CompressionNames)
	return strs
}

// IsACompression returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Compression) IsACompression() bool {
	for _, v := range _CompressionValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for Compression
func (i Compression) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Compression
func (i *Compression) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Compression should be a string, got %s", data)
	}

	var err error
	*i, err = CompressionString(s)
	return err
}

func (i Compression) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Compression) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of Compression: %[1]T(%[1]v)", value)
	}

	val, err := CompressionString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
