// Code generated by "enumer -json -sql -type JobType -trimprefix JobType"; DO NOT EDIT.

//
package geocube

import (
	"database/sql/driver"
	"encoding/json"
	"fmt"
)

const _JobTypeName = "CONSOLIDATIONINGESTIONDELETION"

var _JobTypeIndex = [...]uint8{0, 13, 22, 30}

func (i JobType) String() string {
	if i < 0 || i >= JobType(len(_JobTypeIndex)-1) {
		return fmt.Sprintf("JobType(%d)", i)
	}
	return _JobTypeName[_JobTypeIndex[i]:_JobTypeIndex[i+1]]
}

var _JobTypeValues = []JobType{0, 1, 2}

var _JobTypeNameToValueMap = map[string]JobType{
	_JobTypeName[0:13]:  0,
	_JobTypeName[13:22]: 1,
	_JobTypeName[22:30]: 2,
}

// JobTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func JobTypeString(s string) (JobType, error) {
	if val, ok := _JobTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to JobType values", s)
}

// JobTypeValues returns all values of the enum
func JobTypeValues() []JobType {
	return _JobTypeValues
}

// IsAJobType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i JobType) IsAJobType() bool {
	for _, v := range _JobTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for JobType
func (i JobType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for JobType
func (i *JobType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("JobType should be a string, got %s", data)
	}

	var err error
	*i, err = JobTypeString(s)
	return err
}

func (i JobType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *JobType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := JobTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
