apiVersion: apps/v1
kind: Deployment
metadata:
  name: telepresence
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: telepresence
    spec:
      containers:
        - name: telepresence
          image: datawire/telepresence-k8s:0.109
  selector:
    matchLabels:
      name: telepresence
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: telepresence
  namespace: default
spec:
  podSelector:
    matchLabels:
      name: telepresence
  policyTypes:
    - Egress
  egress:
    - {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: telepresence-to
  namespace: default
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              name: telepresence
      ports:
        - {}
